//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_HMOEntities2 : DbContext
    {
        public DB_HMOEntities2()
            : base("name=DB_HMOEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Maker_tbl> Maker_tbl { get; set; }
        public virtual DbSet<Patients_tbl> Patients_tbl { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vaccination_tbl> Vaccination_tbl { get; set; }
        public virtual DbSet<StatusCOVID19_tbl> StatusCOVID19_tbl { get; set; }
    }
}
