//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patients_tbl()
        {
            this.Vaccination_tbl = new HashSet<Vaccination_tbl>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> HouseNumber { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> MobilePhone { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    
        public virtual StatusCOVID19_tbl StatusCOVID19_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vaccination_tbl> Vaccination_tbl { get; set; }
    }
}
