//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusCOVID19_tbl
    {
        public int PatientId { get; set; }
        public Nullable<System.DateTime> Positive { get; set; }
        public Nullable<System.DateTime> Recovery { get; set; }
    
        public virtual Patients_tbl Patients_tbl { get; set; }
    }
}
